### ISSUE TITLE
How can I use this with Ionic2 app.

### ISSUE THREAD

**Issue by sirKings** [impactmass/symmetrical-octo-garbanzo#18]
I have followed your steps to the later, and the installation was without issues. Unfortunately, probably because of typescript, the InitRavePay function is not exposed as expected. Is there any way around this. A fast response will be appreciated. thanks

**Comment by impactmass** [comment]
Hi @sirKings 

I was just replying you on this [other thread.](https://github.com/impactmass/cordova-rave/issues/11#issuecomment-310713278).

Like you've guessed, it might be a typescript issue. Can you provide a sample of what you have? Maybe i can dig in quickly.

I will also take some time to create a sample of using the lib with Ionic2 (but that might take me awhile (as I'm currently working on other stuffs).

**Comment by impactmass** [comment]
We can leave this open. I'll use it to track progress on this issue.
Like I mentioned, I'll find time and do a setup with Ionic2. I'll update here when I do that. Thanks

**Comment by impactmass** [comment]
One way around this is to call the initRavePay func on the window object. But the typescript compiler will complain about `Property 'initRavePay' does not exist on type 'Window'`. 

Then the compiler warning can be worked around by having a lib.d.ts that extends the window interface to include a type for initRavePay. I've pasted parts of an example that I made below:

/welcome/welcome.ts
```
<ion-content scroll="false">
  <div class="splash-bg"></div>
  <div class="splash-info">
    <div class="splash-logo"></div>
    <div class="splash-intro">
      {{ 'WELCOME_INTRO' | translate }}
    </div>
  </div>
  <div padding>
    <button ion-button block (click)="signup()" class="signup">{{ 'SIGNUP' | translate }}</button>
    <button ion-button block (click)="login()" class="login">{{ 'LOGIN' | translate }}</button>
    <button ion-button block (click)="ravePay()" class="login">{{ 'RAVE' | translate }}</button>
  </div>
</ion-content>
```
/welcome/welcome.ts
```
export class WelcomePage {

  constructor(public navCtrl: NavController) { }

  ravePay() {
    window.initRavePay({
      customer_email: "se@r.c",
      txref: "s23qw3e5rqeasg",
      amount: 1500
    })
  }
}
```
pages/welcome/lib.d.ts
```
interface Window {
  initRavePay: any;
}
```
Let me know if this helps or not @sirKings.
 
It's good to point out that I'm not very familiar with TS, so please point out if this solution violates TS conventions.

**Comment by sirKings** [comment]
Thanks alot, this helps. as for TS conventions, i don't think we have violated any, but if there is any further challenge on this, i will let you know.

**Comment by impactmass** [comment]
Cool. Thank you

**Comment by sirKings** [comment]
Hello, this works on android devices and emulators, unfortunately on ios devices/emulators it loads indefinitely. I have tried debugging it but unfortunately it logs nothing on the console. Once the initRavePay(options) is called, it starts loading but never loads the modal. Please help check that out. Thanks

**Comment by sirKings** [comment]
hello @impactmass

**Comment by impactmass** [comment]
Hi. @sirKings. I'll find some time and check this out. And post findings here

**Comment by impactmass** [comment]
If you have more info that can help debugging this (in case you still take a deeper look), you can also post here 👍

**Comment by teebazz** [comment]
window.initRavePay is not a function. (In 'window.initRavePay({
            customer_email: "se@r.c",
            txref: "s23qw3e5rqeasg",
            amount: 1500
        })', 'window.initRavePay' is undefined)


This was my error tryin it on Ionic 3. Please Help

**Comment by dynacorp** [comment]
Has no one figured out how to use this in ionic 3
