### ISSUE TITLE
Livemode configuration in config.json not working.

### ISSUE THREAD

**Issue by naymon1** [impactmass/symmetrical-octo-garbanzo#27]
Hi ,

I set my config.json this way

```
{
  "PBFPubKey": "FLWPUBK-806f7d09b1e16ebbfb52c13ca3aaf6b5-X",
  "amount": 10,
  "customer_email": "nnamdiijeh@yahoo.com",
  "currency": "NGN",
  "country": "NG",
  "custom_title": "",
  "custom_description": "",
  "redirect_url": "",
  "custom_logo": "",
  "liveMode": "y"
}
```

but it still loads the test script when I load the button, am I doing anything wrong or is this coming from the plugin ?

**Comment by impactmass** [comment]
Hi @naymon1 

One thing to note about the mode setting is that it when you change it's value in your config (from y to no, or vice-versa), re-bundling will be required. So you will need to run `npm run build` again. Have you tried that?

**Comment by impactmass** [comment]
hi @naymon1 

**Correction to my previous statement:** To change from test mode to live move, you'll need to run `npm start` first, input your config values again, then `npm run build`.

This is because the right Rave inline code is fetched from Rave server at the time you input your config values.

**Comment by impactmass** [comment]
You can re-open this is you still have the issue
