### ISSUE TITLE
Steps to connect the Rave Android SDK to Cordova extension

### ISSUE THREAD

**Issue by impactmass** [impactmass/symmetrical-octo-garbanzo#40]
Rave Android SDK: https://github.com/mshoperi/cordova-ravepay

**Comment by mshoperi** [comment]
The following are steps to install the WIP plugin that uses Rave native SDKs for Android and iOS:

1. Install Cordova
```
$ sudo npm install -g cordova
```
2. Create a test app
```
cordova create hello com.example.hello HelloWorld
cd hello
```
3. Add platforms (iOS not working yet)
```
cordova platform add ios
cordova platform add android
```
4. Install the plugin in the test app
```
cordova plugin add https://github.com/mshoperi/cordova-ravepay
```
5. Run the app in the Android emulator
```
cordova run android
```

**Comment by impactmass** [comment]
I looked into this a bit, and I was not clear on a way forward. We can revisit this when we have more info (or please re-open if you have more info)
